### ISSUE TITLE
build: optimise images

### ISSUE THREAD

**Issue by filtercake** [filtercake/filtercake.github.io#8]
- [Installing Imagemagick · Issue #78 · travis-ci/travis-ci](https://github.com/travis-ci/travis-ci/issues/78)
- [rmagick/rmagick: Ruby bindings for ImageMagick](https://github.com/rmagick/rmagick)
- [ImageMagick: Convert, Edit, Or Compose Bitmap Images](http://imagemagick.org/script/index.php)

---
- [Responsive Image Breakpoints Generator by Cloudinary](http://www.responsivebreakpoints.com/)

**Comment by amilajack** [comment]
How would I install imagemagick on an osx build/

**Comment by filtercake** [comment]
@amilajack i use homebrew

- http://brew.sh/
- http://brewformulas.org/Imagemagick
